### PR TITLE
fix skin flickering

### PR DESCRIPTION
**Pull request by Zowpy**

### CODE REVIEW

**Comment by DevDrizzy** [comment]
There isn't skin flickering? I've tested with a very laggy tablist adapter, and never had it.

**Comment by Zowpy** [comment]
When using custom skins the tablists keeps updating the heads even tho they have already been updated and dont need updating.

**Comment by iiAhmedYT** [comment]
Well, small suggestion anyway..

Instead of removing
```java
if (o != this) return false;
```

Instead make it
```java
if (o == this) return true;
```

Should server the same purpose It was intended to make

**Comment by Zowpy** [comment]
> Well, small suggestion anyway..
> 
> Instead of removing
> 
> ```java
> if (o != this) return false;
> ```
> 
> Instead make it
> 
> ```java
> if (o == this) return true;
> ```
> 
> Should server the same purpose It was intended to make

no difference at all

**Comment by hardcorefactions** [comment]
is this related to my issue? (#4)

**Comment by NimxDev** [comment]
i had the same issuse and with this patch it got fixed, it should be implemented on the main branch.

**Pull request merged**
